#pragma once

enum struct TokenType{
    NUMBER, STRING, LIST, NIL, BOOL,
    PLUS, MINUS, MULTIPLY, DIVIDE, MOD, POW,
    EQ, N_EQ, LESS, GREATER, LESS_EQ, GREATER_EQ,
    AND, OR, NOT,
    ASSIGN, PLUS_A, MINUS_A, MULTIPLY_A, DIVIDE_A, MOD_A, POW_A,
    R_S_BRACKET, L_S_BRACKET, R_BRACKET, L_BRACKET, COLON, COMMA,
    IF, ELSE, END, THEN, WHILE, FOR, IN, BREAK, CONTINUE, FUNCTION, RETURN, EOFF,
    IDENTIFIER
};
